/* Auto-generated by genmsg_cpp for file /home/redfox/Desktop/CDIO/msg/circle.msg */
#ifndef CDIO_MESSAGE_CIRCLE_H
#define CDIO_MESSAGE_CIRCLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace CDIO
{
template <class ContainerAllocator>
struct circle_ {
  typedef circle_<ContainerAllocator> Type;

  circle_()
  : centerX(0.0)
  , centerY(0.0)
  {
  }

  circle_(const ContainerAllocator& _alloc)
  : centerX(0.0)
  , centerY(0.0)
  {
  }

  typedef double _centerX_type;
  double centerX;

  typedef double _centerY_type;
  double centerY;


  typedef boost::shared_ptr< ::CDIO::circle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::CDIO::circle_<ContainerAllocator>  const> ConstPtr;
}; // struct circle
typedef  ::CDIO::circle_<std::allocator<void> > circle;

typedef boost::shared_ptr< ::CDIO::circle> circlePtr;
typedef boost::shared_ptr< ::CDIO::circle const> circleConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::CDIO::circle_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::CDIO::circle_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace CDIO

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::CDIO::circle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::CDIO::circle_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::CDIO::circle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b28d7e6fe6bf4c2cda9d06343dd83f7c";
  }

  static const char* value(const  ::CDIO::circle_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb28d7e6fe6bf4c2cULL;
  static const uint64_t static_value2 = 0xda9d06343dd83f7cULL;
};

template<class ContainerAllocator>
struct DataType< ::CDIO::circle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CDIO/circle";
  }

  static const char* value(const  ::CDIO::circle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::CDIO::circle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 centerX\n\
float64 centerY\n\
\n\
";
  }

  static const char* value(const  ::CDIO::circle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::CDIO::circle_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::CDIO::circle_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.centerX);
    stream.next(m.centerY);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct circle_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::CDIO::circle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::CDIO::circle_<ContainerAllocator> & v) 
  {
    s << indent << "centerX: ";
    Printer<double>::stream(s, indent + "  ", v.centerX);
    s << indent << "centerY: ";
    Printer<double>::stream(s, indent + "  ", v.centerY);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CDIO_MESSAGE_CIRCLE_H

