(cl:defpackage CDIO-srv
  (:use )
  (:export
   "CHAPTER2_SRV1"
   "<CHAPTER2_SRV1-REQUEST>"
   "CHAPTER2_SRV1-REQUEST"
   "<CHAPTER2_SRV1-RESPONSE>"
   "CHAPTER2_SRV1-RESPONSE"
   "GET_BATTERY_SRV"
   "<GET_BATTERY_SRV-REQUEST>"
   "GET_BATTERY_SRV-REQUEST"
   "<GET_BATTERY_SRV-RESPONSE>"
   "GET_BATTERY_SRV-RESPONSE"
  ))

